database:
  server: "222.27.255.211:15236"
  username: "SYSDBA_TEST"
  passwd: "SYSDBA"

fileSystem:
  endpoint: "222.27.255.211:19000"
  username: "fileadmin_test"
  passwd: "fileadmin"

log:
  username: "loguser"
  passwd: "SYSDBA1234"
  cidr: "169.254.189.90/16"
  enable: true