server:
  username: "708_USER"
  password: "708_user"
  database-server: "192.168.8.201:5236"
  file-system-server: "192.168.8.201:9000"

log:
  username: "Admin_LOG"
  password: "logmanager"
  cidr: "192.168.8.0/24"
  enable: true