database:
  server: "192.168.8.201:5236"
  username: "CMDADM"
  passwd: "SYSDBA"

fileSystem:
  endpoint: "192.168.8.201:9000"
  username: "CAEadmin"
  passwd: "fileadmin"

log:
  username: "LOG"
  passwd: "logmanager"
  cidr: "192.168.8.0/24"
  enable: true